#INTRODUCTION TO PYTHON 

#WHAT IS PYTHON?

# A PROGRAMMING LANGUAGE IS A SET OF INSTRUCTIONS AND RULES THAT A COMPUTER CAN UNDERSTAND AND EXECUTE.
#  IT'S  A WAY FOR HUMANS TO COMMUNICATE WITH COMPUTERS AND TELL THEM WHAT TO DO.
#  PYTHON IS A HIGH-LEVEL VERSTILE AND WIDELY-USED PROGRAMMING LANGUAGE THAT IS EASY TO LEARN AND EASY TO READ.

#WHY PYTHON?
# 1. EASY TO LEARN
# 2. EASY TO READ
# 3. EASY TO WRITE
# 4. EASY TO MAINTAIN
# 5. WIDE RANGE OF LIBRARIES
# 6. WIDE RANGE OF APPLICATIONS
# 7. OPEN SOURCE
# 8. CROSS-PLATFORM
# 9. HIGH-LEVEL LANGUAGE
# 10. INTERPRETED LANGUAGE
# 11. OBJECT-ORIENTED LANGUAGE
# 12. DYNAMICALLY TYPED LANGUAGE

print("Hello World")

